#include "oaDX11Flags.h"

namespace oaEngineSDK {

Map<BIND,uint32> Flags::FLAGS{
  {BIND::VERTEX,D3D11_BIND_VERTEX_BUFFER},
  {BIND::CONSTANT,D3D11_BIND_CONSTANT_BUFFER},
  {BIND::INDEX,D3D11_BIND_INDEX_BUFFER},
  {BIND::DEPTH_STENCIL,D3D11_BIND_DEPTH_STENCIL}
  };

Map<FILTER, D3D11_FILTER> Flags::FILTER_FLAGS{
  {FILTER::MIN_MAG_MIP_POINT,D3D11_FILTER_MIN_MAG_MIP_POINT},
  {FILTER::MIN_MAG_POINT_MIP_LINEAR,D3D11_FILTER_MIN_MAG_POINT_MIP_LINEAR},
  {FILTER::MIN_POINT_MAG_LINEAR_MIP_POINT,D3D11_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT},
  {FILTER::MIN_POINT_MAG_MIP_LINEAR,D3D11_FILTER_MIN_POINT_MAG_MIP_LINEAR},
  {FILTER::MIN_LINEAR_MAG_MIP_POINT,D3D11_FILTER_MIN_LINEAR_MAG_MIP_POINT},
  {FILTER::MIN_LINEAR_MAG_POINT_MIP_LINEAR,D3D11_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR},
  {FILTER::MIN_MAG_LINEAR_MIP_POINT,D3D11_FILTER_MIN_MAG_LINEAR_MIP_POINT},
  {FILTER::MIN_MAG_MIP_LINEAR,D3D11_FILTER_MIN_MAG_MIP_LINEAR},
  {FILTER::ANISOTROPIC,D3D11_FILTER_ANISOTROPIC},
  {FILTER::COMPARISON_MIN_MAG_MIP_POINT,D3D11_FILTER_COMPARISON_MIN_MAG_MIP_POINT},
  {FILTER::COMPARISON_MIN_MAG_POINT_MIP_LINEAR,D3D11_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR},
  {FILTER::COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT,D3D11_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT},
  {FILTER::COMPARISON_MIN_POINT_MAG_MIP_LINEAR,D3D11_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR},
  {FILTER::COMPARISON_MIN_LINEAR_MAG_MIP_POINT,D3D11_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT},
  {FILTER::COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR,D3D11_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR},
  {FILTER::COMPARISON_MIN_MAG_LINEAR_MIP_POINT,D3D11_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT},
  {FILTER::COMPARISON_MIN_MAG_MIP_LINEAR,D3D11_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR},
  {FILTER::COMPARISON_ANISOTROPIC,D3D11_FILTER_COMPARISON_ANISOTROPIC},
  {FILTER::MINIMUM_MIN_MAG_MIP_POINT,D3D11_FILTER_MINIMUM_MIN_MAG_MIP_POINT},
  {FILTER::MINIMUM_MIN_MAG_POINT_MIP_LINEAR,D3D11_FILTER_MINIMUM_MIN_MAG_POINT_MIP_LINEAR},
  {FILTER::MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT,D3D11_FILTER_MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT},
  {FILTER::MINIMUM_MIN_POINT_MAG_MIP_LINEAR,D3D11_FILTER_MINIMUM_MIN_POINT_MAG_MIP_LINEAR},
  {FILTER::MINIMUM_MIN_LINEAR_MAG_MIP_POINT,D3D11_FILTER_MINIMUM_MIN_LINEAR_MAG_MIP_POINT},
  {FILTER::MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR,D3D11_FILTER_MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR},
  {FILTER::MINIMUM_MIN_MAG_LINEAR_MIP_POINT,D3D11_FILTER_MINIMUM_MIN_MAG_LINEAR_MIP_POINT},
  {FILTER::MINIMUM_MIN_MAG_MIP_LINEAR,D3D11_FILTER_MINIMUM_MIN_MAG_MIP_LINEAR},
  {FILTER::MINIMUM_ANISOTROPIC,D3D11_FILTER_MINIMUM_ANISOTROPIC},
  {FILTER::MAXIMUM_MIN_MAG_MIP_POINT,D3D11_FILTER_MAXIMUM_MIN_MAG_MIP_POINT},
  {FILTER::MAXIMUM_MIN_MAG_POINT_MIP_LINEAR,D3D11_FILTER_MAXIMUM_MIN_MAG_POINT_MIP_LINEAR},
  {FILTER::MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT,D3D11_FILTER_MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT},
  {FILTER::MAXIMUM_MIN_POINT_MAG_MIP_LINEAR,D3D11_FILTER_MAXIMUM_MIN_POINT_MAG_MIP_LINEAR},
  {FILTER::MAXIMUM_MIN_LINEAR_MAG_MIP_POINT,D3D11_FILTER_MAXIMUM_MIN_LINEAR_MAG_MIP_POINT},
  {FILTER::MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR,D3D11_FILTER_MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR},
  {FILTER::MAXIMUM_MIN_MAG_LINEAR_MIP_POINT,D3D11_FILTER_MAXIMUM_MIN_MAG_LINEAR_MIP_POINT},
  {FILTER::MAXIMUM_MIN_MAG_MIP_LINEAR,D3D11_FILTER_MAXIMUM_MIN_MAG_MIP_LINEAR},
  {FILTER::MAXIMUM_ANISOTROPIC,D3D11_FILTER_MAXIMUM_ANISOTROPIC}
};

Map<TEXTURE_ADDRESS_MODE, D3D11_TEXTURE_ADDRESS_MODE> Flags::TEXTURE_ADDRESS_FLAGS{
  {TEXTURE_ADDRESS_MODE::WRAP,D3D11_TEXTURE_ADDRESS_WRAP},
  {TEXTURE_ADDRESS_MODE::MIRROR,D3D11_TEXTURE_ADDRESS_MIRROR},
  {TEXTURE_ADDRESS_MODE::CLAMP,D3D11_TEXTURE_ADDRESS_CLAMP},
  {TEXTURE_ADDRESS_MODE::BORDER,D3D11_TEXTURE_ADDRESS_BORDER},
  {TEXTURE_ADDRESS_MODE::MIRROR_ONCE,D3D11_TEXTURE_ADDRESS_MIRROR_ONCE},  
};

Map<COMPARISON_FUNC, D3D11_COMPARISON_FUNC> Flags::COMPARISON_FLAGS{
  {COMPARISON_FUNC::NEVER,D3D11_COMPARISON_NEVER},
  {COMPARISON_FUNC::LESS,D3D11_COMPARISON_LESS},
  {COMPARISON_FUNC::EQUAL,D3D11_COMPARISON_EQUAL},
  {COMPARISON_FUNC::LESS_EQUAL,D3D11_COMPARISON_LESS_EQUAL},
  {COMPARISON_FUNC::GREATER,D3D11_COMPARISON_GREATER},
  {COMPARISON_FUNC::NOT_EQUAL,D3D11_COMPARISON_NOT_EQUAL},
  {COMPARISON_FUNC::GREATER_EQUAL,D3D11_COMPARISON_GREATER_EQUAL},
  {COMPARISON_FUNC::ALWAYS,D3D11_COMPARISON_ALWAYS}
}; 

Map<FORMAT,DXGI_FORMAT> Flags::FORMATS{
  {FORMAT::D24_UNORM_S8_UINT,DXGI_FORMAT_D24_UNORM_S8_UINT},
  };

}