#include "oaDX11Flags.h"

namespace oaEngineSDK {

Map<BIND::E,uint32> Flags::FLAGS{
  {BIND::kConstant,D3D11_BIND_VERTEX_BUFFER},
  {BIND::kVertex,D3D11_BIND_CONSTANT_BUFFER},
  {BIND::kIndex,D3D11_BIND_INDEX_BUFFER},
  {BIND::kDepthStencil,D3D11_BIND_DEPTH_STENCIL},
  {BIND::kShaderResourse,D3D11_BIND_SHADER_RESOURCE},
  {BIND::kRenderTarget,D3D11_BIND_RENDER_TARGET},
  {BIND::kShaderResourse,D3D11_BIND_SHADER_RESOURCE|D3D11_BIND_RENDER_TARGET},
  };

Map<FILTER::E, D3D11_FILTER> Flags::FILTER_FLAGS{
  //{FILTER::MIN_MAG_MIP_POINT,D3D11_FILTER_MIN_MAG_MIP_POINT},
  {FILTER::kMinMagMipLinear,D3D11_FILTER_MIN_MAG_POINT_MIP_LINEAR},
  /*{FILTER::MIN_POINT_MAG_LINEAR_MIP_POINT,D3D11_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT},
  {FILTER::MIN_POINT_MAG_MIP_LINEAR,D3D11_FILTER_MIN_POINT_MAG_MIP_LINEAR},
  {FILTER::MIN_LINEAR_MAG_MIP_POINT,D3D11_FILTER_MIN_LINEAR_MAG_MIP_POINT},
  {FILTER::MIN_LINEAR_MAG_POINT_MIP_LINEAR,D3D11_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR},
  {FILTER::MIN_MAG_LINEAR_MIP_POINT,D3D11_FILTER_MIN_MAG_LINEAR_MIP_POINT},
  {FILTER::MIN_MAG_MIP_LINEAR,D3D11_FILTER_MIN_MAG_MIP_LINEAR},
  {FILTER::ANISOTROPIC,D3D11_FILTER_ANISOTROPIC},
  {FILTER::COMPARISON_MIN_MAG_MIP_POINT,D3D11_FILTER_COMPARISON_MIN_MAG_MIP_POINT},
  {FILTER::COMPARISON_MIN_MAG_POINT_MIP_LINEAR,D3D11_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR},
  {FILTER::COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT,D3D11_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT},
  {FILTER::COMPARISON_MIN_POINT_MAG_MIP_LINEAR,D3D11_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR},
  {FILTER::COMPARISON_MIN_LINEAR_MAG_MIP_POINT,D3D11_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT},
  {FILTER::COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR,D3D11_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR},
  {FILTER::COMPARISON_MIN_MAG_LINEAR_MIP_POINT,D3D11_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT},
  {FILTER::COMPARISON_MIN_MAG_MIP_LINEAR,D3D11_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR},
  {FILTER::COMPARISON_ANISOTROPIC,D3D11_FILTER_COMPARISON_ANISOTROPIC},
  {FILTER::MINIMUM_MIN_MAG_MIP_POINT,D3D11_FILTER_MINIMUM_MIN_MAG_MIP_POINT},
  {FILTER::MINIMUM_MIN_MAG_POINT_MIP_LINEAR,D3D11_FILTER_MINIMUM_MIN_MAG_POINT_MIP_LINEAR},
  {FILTER::MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT,D3D11_FILTER_MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT},
  {FILTER::MINIMUM_MIN_POINT_MAG_MIP_LINEAR,D3D11_FILTER_MINIMUM_MIN_POINT_MAG_MIP_LINEAR},
  {FILTER::MINIMUM_MIN_LINEAR_MAG_MIP_POINT,D3D11_FILTER_MINIMUM_MIN_LINEAR_MAG_MIP_POINT},
  {FILTER::MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR,D3D11_FILTER_MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR},
  {FILTER::MINIMUM_MIN_MAG_LINEAR_MIP_POINT,D3D11_FILTER_MINIMUM_MIN_MAG_LINEAR_MIP_POINT},
  {FILTER::MINIMUM_MIN_MAG_MIP_LINEAR,D3D11_FILTER_MINIMUM_MIN_MAG_MIP_LINEAR},
  {FILTER::MINIMUM_ANISOTROPIC,D3D11_FILTER_MINIMUM_ANISOTROPIC},
  {FILTER::MAXIMUM_MIN_MAG_MIP_POINT,D3D11_FILTER_MAXIMUM_MIN_MAG_MIP_POINT},
  {FILTER::MAXIMUM_MIN_MAG_POINT_MIP_LINEAR,D3D11_FILTER_MAXIMUM_MIN_MAG_POINT_MIP_LINEAR},
  {FILTER::MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT,D3D11_FILTER_MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT},
  {FILTER::MAXIMUM_MIN_POINT_MAG_MIP_LINEAR,D3D11_FILTER_MAXIMUM_MIN_POINT_MAG_MIP_LINEAR},
  {FILTER::MAXIMUM_MIN_LINEAR_MAG_MIP_POINT,D3D11_FILTER_MAXIMUM_MIN_LINEAR_MAG_MIP_POINT},
  {FILTER::MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR,D3D11_FILTER_MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR},
  {FILTER::MAXIMUM_MIN_MAG_LINEAR_MIP_POINT,D3D11_FILTER_MAXIMUM_MIN_MAG_LINEAR_MIP_POINT},
  {FILTER::MAXIMUM_MIN_MAG_MIP_LINEAR,D3D11_FILTER_MAXIMUM_MIN_MAG_MIP_LINEAR},
  {FILTER::MAXIMUM_ANISOTROPIC,D3D11_FILTER_MAXIMUM_ANISOTROPIC}*/
};

Map<TEXTURE_ADDRESS_MODE::E, D3D11_TEXTURE_ADDRESS_MODE> Flags::TEXTURE_ADDRESS_FLAGS{
  {TEXTURE_ADDRESS_MODE::kWrap,D3D11_TEXTURE_ADDRESS_WRAP},
  {TEXTURE_ADDRESS_MODE::kMirror,D3D11_TEXTURE_ADDRESS_MIRROR},
  {TEXTURE_ADDRESS_MODE::kClamp,D3D11_TEXTURE_ADDRESS_CLAMP},
  {TEXTURE_ADDRESS_MODE::kBorder,D3D11_TEXTURE_ADDRESS_BORDER},
  {TEXTURE_ADDRESS_MODE::kMirrorOnce,D3D11_TEXTURE_ADDRESS_MIRROR_ONCE},  
};

Map<COMPARISON_FUNC::E, D3D11_COMPARISON_FUNC> Flags::COMPARISON_FLAGS{
  {COMPARISON_FUNC::kNever,D3D11_COMPARISON_NEVER},
  {COMPARISON_FUNC::kLess,D3D11_COMPARISON_LESS},
  {COMPARISON_FUNC::kEqual,D3D11_COMPARISON_EQUAL},
  {COMPARISON_FUNC::kLessEqual,D3D11_COMPARISON_LESS_EQUAL},
  {COMPARISON_FUNC::kGreater,D3D11_COMPARISON_GREATER},
  {COMPARISON_FUNC::kNotEqual,D3D11_COMPARISON_NOT_EQUAL},
  {COMPARISON_FUNC::kGreaterEqual,D3D11_COMPARISON_GREATER_EQUAL},
  {COMPARISON_FUNC::kAlways,D3D11_COMPARISON_ALWAYS}
}; 

Map<FORMAT::E,DXGI_FORMAT> Flags::FORMATS{
  {FORMAT::kD24UNormS8UInt,DXGI_FORMAT_D24_UNORM_S8_UINT},
  {FORMAT::kR32G32B32A32Float,DXGI_FORMAT_R32G32B32A32_FLOAT},
  {FORMAT::kB8G8R8A8UnormSRGB,DXGI_FORMAT_B8G8R8A8_UNORM_SRGB}
  };

Map<DS_DIMENSION::E,D3D11_DSV_DIMENSION> Flags::DS_DIMENCIONS{
  {DS_DIMENSION::kUnknown,D3D11_DSV_DIMENSION_UNKNOWN},
  {DS_DIMENSION::kTexture1D,D3D11_DSV_DIMENSION_TEXTURE1D},
  {DS_DIMENSION::kTexture1DArray,D3D11_DSV_DIMENSION_TEXTURE1DARRAY},
  {DS_DIMENSION::kTexture2D,D3D11_DSV_DIMENSION_TEXTURE2D},
  {DS_DIMENSION::kTexture2DArray,D3D11_DSV_DIMENSION_TEXTURE2DARRAY},
  {DS_DIMENSION::kTexture2DMS,D3D11_DSV_DIMENSION_TEXTURE2DMS},
  {DS_DIMENSION::kTexture2DMSArray,D3D11_DSV_DIMENSION_TEXTURE2DMSARRAY},
};

Map<SRV_DIMENSION::E,D3D11_SRV_DIMENSION> Flags::SRV_DIMENCIONS{
  {SRV_DIMENSION::kUnknown,D3D11_SRV_DIMENSION_UNKNOWN},
  {SRV_DIMENSION::kBuffer,D3D11_SRV_DIMENSION_BUFFER},
  {SRV_DIMENSION::kTexture1D, D3D11_SRV_DIMENSION_TEXTURE1D},
  {SRV_DIMENSION::kTexture1DArray,D3D11_SRV_DIMENSION_TEXTURE1DARRAY},
  {SRV_DIMENSION::kTexture2D,D3D11_SRV_DIMENSION_TEXTURE2D},
  {SRV_DIMENSION::kTexture2DArray,D3D11_SRV_DIMENSION_TEXTURE2DARRAY },
  {SRV_DIMENSION::kTexture2DMS,D3D11_SRV_DIMENSION_TEXTURE2DMS},
  {SRV_DIMENSION::kTexture2DMSArray,D3D11_SRV_DIMENSION_TEXTURE2DMSARRAY},
  {SRV_DIMENSION::kTexture3D,D3D11_SRV_DIMENSION_TEXTURE3D},
  {SRV_DIMENSION::kTextureCube,D3D11_SRV_DIMENSION_TEXTURECUBE},
  {SRV_DIMENSION::kTextureCubeArray,D3D11_SRV_DIMENSION_TEXTURECUBEARRAY},
  {SRV_DIMENSION::kBufferEx,D3D11_SRV_DIMENSION_BUFFEREX}
};

Map<PRIMITIVE_TOPOLOGY::E,D3D11_PRIMITIVE_TOPOLOGY> Flags::PRIMITIVE_TOPOLOGYS{
  {PRIMITIVE_TOPOLOGY::kPointList,   D3D11_PRIMITIVE_TOPOLOGY_POINTLIST},
  {PRIMITIVE_TOPOLOGY::kLineList,    D3D11_PRIMITIVE_TOPOLOGY_LINELIST},
  {PRIMITIVE_TOPOLOGY::kLineStrip,   D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP}, 
  {PRIMITIVE_TOPOLOGY::kTrianlgeList,D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST},	 
  {PRIMITIVE_TOPOLOGY::kTrianlgeStrip,D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP}
};

}