
#pragma once

namespace oaEngineSDK{
class Shader;
class Buffer;
class VertexBuffer;
class IndexBuffer;
class SamplerState;
struct SamplerDesc;
class RenderTarget;
class DepthStencil;
struct DepthStencilDesc;
class Mesh;
class Texture;
class Model;
class Material;
class Skeleton;
struct SkeletalNode;
class Animation;
struct AnimNode;
class Actor;
class Component;
class Path;
class GraphicsComponent;
class SkeletalComponent;
class AnimationComponent;
class CameraComponent;
class Scene;
class ShaderProgram;
class Camera;
class Scene;
class Image;
class Resourse;
class Rasterizer;
class Renderer;
class Blender;
class DebugMesh;
}